### ISSUE TITLE
REAL-PD generate Northwestern Features

### ISSUE THREAD

**Issue by sieberts** [Sage-Bionetworks/beat-pd#4]
Run Northwestern feature extraction pipeline on REAL-PD segments.

**Comment by nshawen** [comment]
The REAL-PD Features are in the extracted features folder in Synapse and should be good to use. I had to remove some of the windows of smartphone accelerometer data because the signal was constant in some of the windows. This led to some features not computing properly. I'm guessing this was because the phone was not being carried and was left somewhere (maybe to charge). I didn't have any similar issues with the smartwatch data, but there may be additional data segments from the phone that were near-constant and might not actually be informative. It could be useful to filter windows out based on acceleration variance in that case.

**Comment by sieberts** [comment]
Nick cleaned features with low variation.
